package Modelo;
// Generated 31 ene. 2021 20:57:12 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriasNew generated by hbm2java
 */
public class CategoriasNew implements java.io.Serializable {

	private Integer id;
	private String categoria;
	private String descripcion;
	private Set productosNews = new HashSet(0);

	public CategoriasNew() {
	}

	public CategoriasNew(String categoria) {
		this.categoria = categoria;
	}

	public CategoriasNew(String categoria, String descripcion, Set productosNews) {
		this.categoria = categoria;
		this.descripcion = descripcion;
		this.productosNews = productosNews;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getProductosNews() {
		return this.productosNews;
	}

	public void setProductosNews(Set productosNews) {
		this.productosNews = productosNews;
	}

}
