package Modelo;
// Generated 31 ene. 2021 20:57:12 by Hibernate Tools 5.4.21.Final

/**
 * Superusuarios generated by hbm2java
 */
public class Superusuarios implements java.io.Serializable {

	private Integer idUser;
	private String apellidos;
	private String nombre;
	private String user;

	public Superusuarios() {
	}

	public Superusuarios(String apellidos, String nombre, String user) {
		this.apellidos = apellidos;
		this.nombre = nombre;
		this.user = user;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
