package Modelo;
// Generated 31 ene. 2021 20:57:12 by Hibernate Tools 5.4.21.Final

/**
 * TotalesMensuales generated by hbm2java
 */
public class TotalesMensuales implements java.io.Serializable {

	private TotalesMensualesId id;

	public TotalesMensuales() {
	}

	public TotalesMensuales(TotalesMensualesId id) {
		this.id = id;
	}

	public TotalesMensualesId getId() {
		return this.id;
	}

	public void setId(TotalesMensualesId id) {
		this.id = id;
	}

}
